### ISSUE TITLE
How save it's files to local server?

### ISSUE THREAD

**Issue by Sv9t** [spapas/django-pdf-guide#1]
Hi! I generated pdf file in browser, but how save it to local server?

**Comment by spapas** [comment]
Hello! You mean that you want to save the generated pdf file in a django model instance (in a FileField) so that you'll be able to access it later?

**Comment by Sv9t** [comment]
No, I don't want to save pdf in a django model. I want to save pdf on server (write to disk the generated pdf) without view in browser. I solved it in this way:
```
# views.py
class GeneratePdf(View):
    """
    This is page generate pdf, save pdf in path /opt/pdf/
    and redirect to home page
    """
    def get(self, request, *args, **kwargs):
        context = {
            'status': status
            }
        with open('/opt/pdf/mypdf.pdf', 'wb') as output:
            template = get_template('table_pdf/index_pdf.html')
            html = template.render(context)
            pdf = pisa.CreatePDF(html.encode("UTF-8"),
                                 output, encoding='UTF-8', link_callback=fetch_resources)
        return redirect('home_page')
```
Do you have anything to add or modify in my code? Please, write your decision about saving pdf in a django model! I'd like to know it.

PS Your "django-pdf-guide" has helped me a lot. Thanks!

**Comment by spapas** [comment]
Hello thank you for your kind words!

I think that's the proper way to do it. Just use a django setting to store the folder you're saving the file instead of harcoding it there.

Concerning the way to save the generated file in a django file field, since you'll create the bytes of the pdf file on the fly (and not save it on disk) you should use ContentFile. Here's a good explanation: https://stackoverflow.com/questions/7514964/django-how-to-create-a-file-and-save-it-to-a-models-filefield
